In [1]:
#Empty List
my_list = []
print(my_list)

[]

In [13]:
#creating list with numbers
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
print(list3[0])
print(list1[-1])
print(list4[6])
print(list2[-9])
print(list5[0])
print(list6[3])
print(list7[8])
print(list8[3])
print(list9[-2])
print(list10[-4])

#creating list with strings
batch_1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch_2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch_4 = ["raju","ramesh","suresh","bheem","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju"]
batch_6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash"]
batch_9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam"]
print(batch_1[0])
print(batch_2[-1])
print(batch_3[-4])
print(batch_4[3])
print(batch_5[2])
print(batch_6[0])
print(batch_7[1])
print(batch_8[-2])
print(batch_9[-3])
print(batch_10[-5])

11
10
70
13
12
20
12
51
86
37
vasu
kajal
chandhu
bheem
vinith
teja
kavya
nithin
sai
fhanni

In [21]:
#Slicing (numbers) (n-1 for +ve and n+1 for -ve)
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
print(list1[1:5])
print(list3[2:9])
print(list2[1:3])
print(list4[-9:-2])
print(list5[2:4])
print(list6[-3:-2])
print(list7[9:-6])
print(list8[5:6])
print(list9[ :8])
print(list10[-9: ])

#slicing (strings)
batch_1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch_2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch_4 = ["raju","ramesh","suresh","bheem","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju"]
batch_6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash"]
batch_9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam"]
print(batch_1[2:4])
print(batch_2[3:5])
print(batch_3[-4:-1])
print(batch_4[-5:4])
print(batch_5[0:3])
print(batch_6[2:8])
print(batch_7[5:9])
print(batch_8[ :4])
print(batch_9[-1: ])
print(batch_10[0: ])

[2, 3, 4, 5]
[33, 44, 55, 66, 77, 88, 99]
[12, 13]
[10, 20, 30, 40, 50, 60, 70]
[45, 65]
[4]
[]
[71]
[41, 51, 61, 34, 26, 17, 19, 32]
[82, 73, 64, 51, 26, 37, 4, 8, 59]
['pranay', 'lokesh']
['bhavya', 'kajal']
['chandhu', 'aniketh', 'manoj']
['raju', 'ramesh', 'suresh', 'bheem']
['sri', 'vardhan', 'vinith']
['vamsi', 'rajesh', 'mahesh']
[]
['charan', 'prashanth', 'ganesh', 'nithin']
['bhaskar']
['fhanni', 'vamshi', 'nawaz', 'aman', 'asmam']

In [23]:
#list Operators
#1) Concatenation (numbers)
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
print(list1 + list2)
print(list3 + list4)
print(list4 + list5)
print(list3 + list4)
print(list6 + list1)
print(list7 + list2)
print(list10 + list1)
print(list9 + list10)
print(list2 + list8)
print(list1 + list4)

#Strings
batch_1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch_2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch_4 = ["raju","ramesh","suresh","bheem","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju"]
batch_6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash"]
batch_9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam"]
print(batch_1 + batch_2)
print(batch_3 + batch_4)
print(batch_4 + batch_5)
print(batch_1 + batch_6)
print(batch_7 + batch_2)
print(batch_8 + batch_9)
print(batch_7 + batch_10)
print(batch_2 + batch_9)
print(batch_1 + batch_7)
print(batch_4 + batch_1)
print(batch_10 + batch_1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20]
[11, 22, 33, 44, 55, 66, 77, 88, 99, 10, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 12, 32, 45, 65, 45, 76, 23, 5, 7, 0]
[11, 22, 33, 44, 55, 66, 77, 88, 99, 10, 20, 30, 40, 50, 60, 70, 80, 90]
[32, 54, 92, 20, 13, 54, 12, 4, 45, 74, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20]
[91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[41, 51, 61, 34, 26, 17, 19, 32, 86, 44, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59]
[11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 20, 30, 40, 50, 60, 70, 80, 90]
['vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'kavya', 'khyathi', 'bhavana', 'bhavya', 'kajal']
['gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil']
['raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'sri', 'vardhan', 'vinith', 'prakash', 'raju']
['vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'teja', 'venky', 'vamsi', 'rajesh', 'mahesh']
['gopal', 'kavya', 'sindhu', 'navatha', 'manasa', 'kavya', 'khyathi', 'bhavana', 'bhavya', 'kajal']
['charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'raghu', 'sandeep', 'akhil', 'sai', 'vinay', 'bhaskar']
['gopal', 'kavya', 'sindhu', 'navatha', 'manasa', 'fhanni', 'vamshi', 'nawaz', 'aman', 'asmam']
['kavya', 'khyathi', 'bhavana', 'bhavya', 'kajal', 'raghu', 'sandeep', 'akhil', 'sai', 'vinay', 'bhaskar']
['vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'gopal', 'kavya', 'sindhu', 'navatha', 'manasa']
['raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'vasu', 'kittu', 'pranay', 'lokesh', 'shiva']
['fhanni', 'vamshi', 'nawaz', 'aman', 'asmam', 'vasu', 'kittu', 'pranay', 'lokesh', 'shiva']

In [25]:
#2) Repetition (Numbers)
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
print(list1 * 3)
print(list2 * 2)
print(list3 * 4)
print(list4 * 7)
print(list5 * 0)
print(list6 * 2)
print(list7 * 7)
print(list8 * 8)
print(list9 * 1)
print(list10 * 9)

#Strings
batch_1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch_2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch_4 = ["raju","ramesh","suresh","bheem","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju"]
batch_6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash"]
batch_9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam"]
print(batch_1 * 4)
print(batch_2 * 1)
print(batch_3 * 5)
print(batch_4 * 10)
print(batch_5 * 6)
print(batch_6 * 7)
print(batch_7 * 2)
print(batch_8 * 8)
print(batch_9 * 3)
print(batch_10 * 4)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20, 11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20]
[11, 22, 33, 44, 55, 66, 77, 88, 99, 11, 22, 33, 44, 55, 66, 77, 88, 99, 11, 22, 33, 44, 55, 66, 77, 88, 99, 11, 22, 33, 44, 55, 66, 77, 88, 99]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20, 30, 40, 50, 60, 70, 80, 90]
[]
[32, 54, 92, 20, 13, 54, 12, 4, 45, 74, 32, 54, 92, 20, 13, 54, 12, 4, 45, 74]
[10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 19, 18, 17, 16, 15, 14, 13, 12, 11]
[21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101]
[41, 51, 61, 34, 26, 17, 19, 32, 86, 44]
[91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 91, 82, 73, 64, 51, 26, 37, 4, 8, 59]
['vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'vasu', 'kittu', 'pranay', 'lokesh', 'shiva']
['kavya', 'khyathi', 'bhavana', 'bhavya', 'kajal']
['gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan', 'gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan', 'gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan', 'gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan', 'gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan']
['raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'raju', 'ramesh', 'suresh', 'bheem', 'akhil']
['sri', 'vardhan', 'vinith', 'prakash', 'raju', 'sri', 'vardhan', 'vinith', 'prakash', 'raju', 'sri', 'vardhan', 'vinith', 'prakash', 'raju', 'sri', 'vardhan', 'vinith', 'prakash', 'raju', 'sri', 'vardhan', 'vinith', 'prakash', 'raju', 'sri', 'vardhan', 'vinith', 'prakash', 'raju']
['teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'teja', 'venky', 'vamsi', 'rajesh', 'mahesh']
['gopal', 'kavya', 'sindhu', 'navatha', 'manasa', 'gopal', 'kavya', 'sindhu', 'navatha', 'manasa']
['charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'charan', 'prashanth', 'ganesh', 'nithin', 'yash']
['raghu', 'sandeep', 'akhil', 'sai', 'vinay', 'bhaskar', 'raghu', 'sandeep', 'akhil', 'sai', 'vinay', 'bhaskar', 'raghu', 'sandeep', 'akhil', 'sai', 'vinay', 'bhaskar']
['fhanni', 'vamshi', 'nawaz', 'aman', 'asmam', 'fhanni', 'vamshi', 'nawaz', 'aman', 'asmam', 'fhanni', 'vamshi', 'nawaz', 'aman', 'asmam', 'fhanni', 'vamshi', 'nawaz', 'aman', 'asmam']

In [29]:
#methods
#1) append()  (numbers)
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
list1.append(11)
print(list1)
list2.append(21)
print(list2)
list3.append(1)
print(list3)
list4.append(32)
print(list4)
list5.append(43)
print(list5)
list6.append(10)
print(list6)
list7.append(0)
print(list7)
list8.append(2)
print(list8)
list9.append(111)
print(list9)
list10.append(6)
print(list10)

#Strings
batch_1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch_2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch_4 = ["raju","ramesh","suresh","bheem","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju"]
batch_6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash"]
batch_9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam"]
batch_1.append("mahi")
print(batch_1)
batch_2.append("sindhu")
print(batch_2)
batch_3.append("ashok")
print(batch_3)
batch_4.append("kishor")
print(batch_4)
batch_5.append("asman")
print(batch_5)
batch_6.append("kamala")
print(batch_6)
batch_7.append("koushik")
print(batch_7)
batch_8.append("swapna")
print(batch_8)
batch_9.append("pranay")
print(batch_9)
batch_10.append("gopal")
print(batch_10)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20, 21]
[11, 22, 33, 44, 55, 66, 77, 88, 99, 1]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 32]
[12, 32, 45, 65, 45, 76, 23, 5, 7, 0, 43]
[32, 54, 92, 20, 13, 54, 12, 4, 45, 74, 10]
[10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 0]
[21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 2]
[41, 51, 61, 34, 26, 17, 19, 32, 86, 44, 111]
[91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 6]
['vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'mahi']
['kavya', 'khyathi', 'bhavana', 'bhavya', 'kajal', 'sindhu']
['gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan', 'ashok']
['raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'kishor']
['sri', 'vardhan', 'vinith', 'prakash', 'raju', 'asman']
['teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'kamala']
['gopal', 'kavya', 'sindhu', 'navatha', 'manasa', 'koushik']
['charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'swapna']
['raghu', 'sandeep', 'akhil', 'sai', 'vinay', 'bhaskar', 'pranay']
['fhanni', 'vamshi', 'nawaz', 'aman', 'asmam', 'gopal']

In [49]:
#2)extend()
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
list1_extend = 11,12,13
list1.extend(list1_extend)
print(list1)
list2_extend = 21,22,23
list2.extend(list2_extend)
print(list2)
list3_extend = 111,222,333
list3.extend(list3_extend)
print(list3)
list4_extend = 100,110,120
list4.extend(list4_extend)
print(list4)
list5_extend = 11,54,65
list5.extend(list5_extend)
print(list5)
list6_extend = 32,55,87
list6.extend(list6_extend)
print(list6)
list7_extend = 65,23,87
list7.extend(list7_extend)
print(list7)
list8_extend = 43,8,456
list8.extend(list8_extend)
print(list8)
list9_extend = 12,4,87
list9.extend(list9_extend)
print(list9)
list10_extend = 3,7,5
list10.extend(list10_extend)
print(list10)


#Strings
batch1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch4 = ["raju","ramesh","suresh","bheem","akhil"]
batch5 = ["sri","vardhan","vinith","prakash","raju"]
batch6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch8 = ["charan","prashanth","ganesh","nithin","yash"]
batch9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch10 = ["fhanni","vamshi","nawaz","aman","asmam"]
batch1_extend = "ramu","raghu"
batch1.extend(batch1_extend)
print(batch1)
batch2_extend = "abc","xyz"
batch2.extend(batch2_extend)
print(batch2)
batch3_extend = "rajesh","ramesh"
batch3.extend(batch3_extend)
print(batch3)
batch4_extend = "ramesh","potti"
batch4.extend(batch4_extend)
print(batch4)
batch5_extend = "qwe","rty"
batch5.extend(batch5_extend)
print(batch5)
batch6_extend = "dfg","asdf"
batch6.extend(batch6_extend)
print(batch6)
batch7_extend = "xcvb","wdf"
batch7.extend(batch7_extend)
print(batch7)
batch8_extend = "alrdt","cntrl"
batch8.extend(batch8_extend)
print(batch8)
batch9_extend = "lkjh","lksvd"
batch9.extend(batch9_extend)
print(batch9)
batch10_extend = "qwerty","asdfjhgf"
batch10.extend(batch10_extend)
print(batch10)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
[11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 222, 333]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]
[12, 32, 45, 65, 45, 76, 23, 5, 7, 0, 11, 54, 65]
[32, 54, 92, 20, 13, 54, 12, 4, 45, 74, 32, 55, 87]
[10, 19, 18, 17, 16, 15, 14, 13, 12, 11, 65, 23, 87]
[21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 43, 8, 456]
[41, 51, 61, 34, 26, 17, 19, 32, 86, 44, 12, 4, 87]
[91, 82, 73, 64, 51, 26, 37, 4, 8, 59, 3, 7, 5]
['vasu', 'kittu', 'pranay', 'lokesh', 'shiva', 'ramu', 'raghu']
['kavya', 'khyathi', 'bhavana', 'bhavya', 'kajal', 'abc', 'xyz']
['gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan', 'rajesh', 'ramesh']
['raju', 'ramesh', 'suresh', 'bheem', 'akhil', 'ramesh', 'potti']
['sri', 'vardhan', 'vinith', 'prakash', 'raju', 'qwe', 'rty']
['teja', 'venky', 'vamsi', 'rajesh', 'mahesh', 'dfg', 'asdf']
['gopal', 'kavya', 'sindhu', 'navatha', 'manasa', 'xcvb', 'wdf']
['charan', 'prashanth', 'ganesh', 'nithin', 'yash', 'alrdt', 'cntrl']
['raghu', 'sandeep', 'akhil', 'sai', 'vinay', 'bhaskar', 'lkjh', 'lksvd']
['fhanni', 'vamshi', 'nawaz', 'aman', 'asmam', 'qwerty', 'asdfjhgf']

In [53]:
#3)Insert
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
list1.insert(1,2)
print(list1)
list2.insert(15,16)
print(list2)
list3.insert(22,40)
print(list3)
list4.insert(30,32)
print(list4)
list5.insert(2,12)
print(list5)
list6.insert(3,23)
print(list6)
list7.insert(8,111)
print(list7)
list8.insert(5,11222)
print(list8)
list9.insert(7,4545)
print(list9)
list10.insert(6,100000)
print(list10)

[1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[11, 12, 13, 14, 14, 15, 16, 17, 18, 19, 20, 16]
[11, 22, 33, 44, 55, 66, 77, 88, 99, 40]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 32]
[12, 32, 12, 45, 65, 45, 76, 23, 5, 7, 0]
[32, 54, 92, 23, 20, 13, 54, 12, 4, 45, 74]
[10, 19, 18, 17, 16, 15, 14, 13, 111, 12, 11]
[21, 31, 41, 51, 61, 11222, 71, 81, 91, 100, 101]
[41, 51, 61, 34, 26, 17, 19, 4545, 32, 86, 44]
[91, 82, 73, 64, 51, 26, 100000, 37, 4, 8, 59]

In [61]:
#4) remove
list1 = [1,2,3,4,5,6,7,8,9,5,5,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
list1.remove(5)
print(list1)
list2.remove(14)
print(list2)
list3.remove(33)
print(list3)
list4.remove(70)
print(list4)
list5.remove(45)
print(list5)
list6.remove(20)
print(list6)
list7.remove(17)
print(list7)
list8.remove(51)
print(list8)
list9.remove(86)
print(list9)
list10.remove(26)
print(list10)

batch1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch4 = ["raju","ramesh","suresh","bheem","akhil"]
batch5 = ["sri","vardhan","vinith","prakash","raju"]
batch6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch8 = ["charan","prashanth","ganesh","nithin","yash"]
batch9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch10 = ["fhanni","vamshi","nawaz","aman","asmam"]
batch1.remove("shiva")
print(batch1)
batch2.remove("kajal")
print(batch2)
batch3.remove("gopal")
print(batch3)
batch4.remove("ramesh")
print(batch4)
batch5.remove("prakash")
print(batch5)
batch6.remove("vamsi")
print(batch6)
batch7.remove("manasa")
print(batch7)
batch8.remove("yash")
print(batch8)
batch9.remove("sai")
print(batch9)
batch10.remove("aman")
print(batch10)

[1, 2, 3, 4, 6, 7, 8, 9, 5, 5, 10]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[11, 22, 44, 55, 66, 77, 88, 99]
[10, 20, 30, 40, 50, 60, 80, 90]
[12, 32, 65, 45, 76, 23, 5, 7, 0]
[32, 54, 92, 13, 54, 12, 4, 45, 74]
[10, 19, 18, 16, 15, 14, 13, 12, 11]
[21, 31, 41, 61, 71, 81, 91, 100, 101]
[41, 51, 61, 34, 26, 17, 19, 32, 44]
[91, 82, 73, 64, 51, 37, 4, 8, 59]
['vasu', 'kittu', 'pranay', 'lokesh']
['kavya', 'khyathi', 'bhavana', 'bhavya']
['chandhu', 'aniketh', 'manoj', 'vardhan']
['raju', 'suresh', 'bheem', 'akhil']
['sri', 'vardhan', 'vinith', 'raju']
['teja', 'venky', 'rajesh', 'mahesh']
['gopal', 'kavya', 'sindhu', 'navatha']
['charan', 'prashanth', 'ganesh', 'nithin']
['raghu', 'sandeep', 'akhil', 'vinay', 'bhaskar']
['fhanni', 'vamshi', 'nawaz', 'asmam']

In [71]:
#5) Pop()
list1 = [1,2,3,4,5,6,7,8,9,5,5,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
poped_element = list1.pop(6)
print(list1)
print(poped_element)
poped_element = list2.pop(3)
print(list2)
print(poped_element)
poped_element = list3.pop(2)
print(list3)
print(poped_element)
poped_element = list4.pop(7)
print(list4)
print(poped_element)
poped_element = list5.pop(7)
print(list5)
print(poped_element)
poped_element = list6.pop(3)
print(list6)
print(poped_element)
poped_element = list7.pop(4)
print(list7)
print(poped_element)
poped_element = list8.pop(9)
print(list8)
print(poped_element)
poped_element = list9.pop(5)
print(list9)
print(poped_element)
poped_element = list10.pop(9)
print(list10)
print(poped_element)

batch1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch4 = ["raju","ramesh","suresh","bheem","akhil"]
batch5 = ["sri","vardhan","vinith","prakash","raju"]
batch6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch8 = ["charan","prashanth","ganesh","nithin","yash"]
batch9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch10 = ["fhanni","vamshi","nawaz","aman","asmam"]

poped_element = batch1.pop(3)
print(batch1)
print(poped_element)
poped_element = batch2.pop(2)
print(batch2)
print(poped_element)
poped_element = batch3.pop(4)
print(batch3)
print(poped_element)
poped_element = batch4.pop(2)
print(batch4)
print(poped_element)
poped_element = batch5.pop(2)
print(batch5)
print(poped_element)
poped_element = batch6.pop(4)
print(batch6)
print(poped_element)
poped_element = batch7.pop(2)
print(batch7)
print(poped_element)
poped_element = batch8.pop(3)
print(batch8)
print(poped_element)
poped_element = batch9.pop(4)
print(batch9)
print(poped_element)
poped_element = batch10.pop(3)
print(batch10)
print(poped_element)

[1, 2, 3, 4, 5, 6, 8, 9, 5, 5, 10]
7
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
14
[11, 22, 44, 55, 66, 77, 88, 99]
33
[10, 20, 30, 40, 50, 60, 70, 90]
80
[12, 32, 45, 65, 45, 76, 23, 7, 0]
5
[32, 54, 92, 13, 54, 12, 4, 45, 74]
20
[10, 19, 18, 17, 15, 14, 13, 12, 11]
16
[21, 31, 41, 51, 61, 71, 81, 91, 100]
101
[41, 51, 61, 34, 26, 19, 32, 86, 44]
17
[91, 82, 73, 64, 51, 26, 37, 4, 8]
59
['vasu', 'kittu', 'pranay', 'shiva']
lokesh
['kavya', 'khyathi', 'bhavya', 'kajal']
bhavana
['gopal', 'chandhu', 'aniketh', 'manoj']
vardhan
['raju', 'ramesh', 'bheem', 'akhil']
suresh
['sri', 'vardhan', 'prakash', 'raju']
vinith
['teja', 'venky', 'vamsi', 'rajesh']
mahesh
['gopal', 'kavya', 'navatha', 'manasa']
sindhu
['charan', 'prashanth', 'ganesh', 'yash']
nithin
['raghu', 'sandeep', 'akhil', 'sai', 'bhaskar']
vinay
['fhanni', 'vamshi', 'nawaz', 'asmam']
aman

In [75]:
#6) Index
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,90]
list5 = [12,32,45,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
index = list1.index(7)
print(index)
index = list2.index(20)
print(index)
index = list3.index(77)
print(index)
index = list4.index(30)
print(index)
index = list5.index(65)
print(index)
index = list6.index(74)
print(index)
index = list7.index(12)
print(index)
index = list8.index(81)
print(index)
index = list9.index(44)
print(index)
index = list10.index(91)
print(index)

#Strings
batch1 = ["vasu","kittu","pranay","lokesh","shiva"]
batch2 = ["kavya","khyathi","bhavana","bhavya","kajal"]
batch3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch4 = ["raju","ramesh","suresh","bheem","akhil"]
batch5 = ["sri","vardhan","vinith","prakash","raju"]
batch6 = ["teja","venky","vamsi","rajesh","mahesh"]
batch7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch8 = ["charan","prashanth","ganesh","nithin","yash"]
batch9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar"]
batch10 = ["fhanni","vamshi","nawaz","aman","asmam"]
index = batch1.index("lokesh")
print(index)
index = batch2.index("bhavana")
print(index)
index = batch3.index("aniketh")
print(index)
index = batch4.index("raju")
print(index)
index = batch5.index("raju")
print(index)
index = batch6.index("mahesh")
print(index)
index = batch7.index("gopal")
print(index)
index = batch8.index("ganesh")
print(index)
index = batch9.index("bhaskar")
print(index)
index = batch10.index("nawaz")
print(index)

6
10
6
2
3
9
8
6
9
0
3
2
2
0
4
4
0
2
5
2

In [87]:
#7)count
list1 = [1,2,3,4,5,6,7,8,9,2,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,40,40,40,90]
list5 = [12,32,5,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,10,10,10,10,10,10,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,61,51,51,51,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]
count = list1.count(2)
print(count)
count = list2.count(14)
print(count)
count = list3.count(11)
print(count)
count = list4.count(40)
print(count)
count = list5.count(5)
print(count)
count = list6.count(4)
print(count)
count = list7.count(10)
print(count)
count = list8.count(101)
print(count)
count = list9.count(51)
print(count)
count = list10.count(100)
print(count)

batch_1 = ["vasu","kittu","kittu","pranay","lokesh","kittu","shiva"]
batch_2 = ["kavya","khyathi","bhavana","bhavya","kajal","bhavana","bhavana","bhavana"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan","aniketh","aniketh","aniketh","aniketh"]
batch_4 = ["raju","ramesh","suresh","bheem","ramesh","ramesh","ramesh","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju","prakash","prakash"]
batch_6 = ["teja","venky","vamsi","rajesh","vamsi","mahesh","vamsi"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa","kavya","kavya","kavya","kavya"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash","prashanth","prashanth","prashanth"]
batch_9 = ["raghu","sandeep","akhil","sai","vinay","bhaskar","bhaskar","bhaskar","bhaskar","bhaskar","bhaskar","bhaskar","bhaskar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam","nawaz","nawaz","nawaz","nawaz"]

count = batch_1.count("kittu")
print(count)
count = batch_2.count("bhavana")
print(count)
count = batch_3.count("aniketh")
print(count)
count = batch_4.count("ramesh")
print(count)
count = batch_5.count("prakash")
print(count)
count = batch_6.count("vamsi")
print(count)
count = batch_7.count("kavya")
print(count)
count = batch_8.count("prashanth")
print(count)
count = batch_9.count("bhaskar")
print(count)
count = batch_10.count("nawaz")
print(count)

2
2
1
4
2
1
7
1
4
0
3
4
5
4
3
3
5
4
8
5

In [95]:
#8) Sort
list1 = [9,8,7,6,5,4,3,2,1]
list2 = [99,77,66,55,44,33,88,11,22]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,40,40,40,90]
list5 = [12,32,5,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,10,10,10,10,10,10,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,61,51,51,51,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]

list1.sort()
print(list1)
list2.sort()
print(list2)
list3.sort()
print(list3)
list4.sort()
print(list4)
list5.sort()
print(list5)
list6.sort()
print(list6)
list7.sort()
print(list7)
list8.sort()
print(list8)
list9.sort()
print(list9)
list10.sort()
print(list10)

batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
batch_2 = ["kavya","khyathi","BHAVANA","bhavya","kajal"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch_4 = ["raju","ramesh","SUresh","bheem","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju"]
batch_6 = ["teja","Venky","vamsi","rajesh","mahesh"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash"]
batch_9 = ["raghu","sandeep","akhil","Sai","vinay","bhaSkar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam"]

batch_1.sort()
print(batch_1)
batch_2.sort()
print(batch_2)
batch_3.sort()
print(batch_3)
batch_4.sort()
print(batch_4)
batch_5.sort()
print(batch_5)
batch_6.sort()
print(batch_6)
batch_7.sort()
print(batch_7)
batch_8.sort()
print(batch_8)
batch_9.sort()
print(batch_9)
batch_10.sort()
print(batch_10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 22, 33, 44, 55, 66, 77, 88, 99]
[11, 22, 33, 44, 55, 66, 77, 88, 99]
[10, 20, 30, 40, 40, 40, 40, 50, 60, 70, 80, 90]
[0, 5, 5, 7, 12, 23, 32, 45, 65, 76]
[4, 12, 13, 20, 32, 45, 54, 54, 74, 92]
[10, 10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[21, 31, 41, 51, 61, 71, 81, 91, 100, 101]
[17, 17, 19, 26, 32, 34, 41, 44, 51, 51, 51, 51, 61, 61, 86]
[4, 8, 26, 37, 51, 59, 64, 73, 82, 91]
['Pranay', 'kittu', 'lokEsh', 'shiva', 'vasu']
['BHAVANA', 'bhavya', 'kajal', 'kavya', 'khyathi']
['aniketh', 'chandhu', 'gopal', 'manoj', 'vardhan']
['SUresh', 'akhil', 'bheem', 'raju', 'ramesh']
['prakash', 'raju', 'sri', 'vardhan', 'vinith']
['Venky', 'mahesh', 'rajesh', 'teja', 'vamsi']
['gopal', 'kavya', 'manasa', 'navatha', 'sindhu']
['charan', 'ganesh', 'nithin', 'prashanth', 'yash']
['Sai', 'akhil', 'bhaSkar', 'raghu', 'sandeep', 'vinay']
['aman', 'asmam', 'fhanni', 'nawaz', 'vamshi']

In [99]:
#9) reverse()
list1 = [9,8,7,6,5,4,3,2,1]
list2 = [99,77,66,55,44,33,88,11,22]
list3 = [11,22,33,44,55,66,77,88,99]
list4 = [10,20,30,40,50,60,70,80,40,40,40,90]
list5 = [12,32,5,65,45,76,23,5,7,0]
list6 = [32,54,92,20,13,54,12,4,45,74]
list7 = [10,19,18,17,16,15,14,13,10,10,10,10,10,10,12,11]
list8 = [21,31,41,51,61,71,81,91,100,101]
list9 = [41,51,61,34,26,17,61,51,51,51,17,19,32,86,44]
list10 = [91,82,73,64,51,26,37,4,8,59]

list1.reverse()
print(list1)
list2.reverse()
print(list2)
list3.reverse()
print(list3)
list4.reverse()
print(list4)
list5.reverse()
print(list5)
list6.reverse()
print(list6)
list7.reverse()
print(list7)
list8.reverse()
print(list8)
list9.reverse()
print(list9)
list10.reverse()
print(list10)

batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
batch_2 = ["kavya","khyathi","BHAVANA","bhavya","kajal"]
batch_3 = ["gopal","chandhu","aniketh","manoj","vardhan"]
batch_4 = ["raju","ramesh","SUresh","bheem","akhil"]
batch_5 = ["sri","vardhan","vinith","prakash","raju"]
batch_6 = ["teja","Venky","vamsi","rajesh","mahesh"]
batch_7 = ["gopal","kavya","sindhu","navatha","manasa"]
batch_8 = ["charan","prashanth","ganesh","nithin","yash"]
batch_9 = ["raghu","sandeep","akhil","Sai","vinay","bhaSkar"]
batch_10 = ["fhanni","vamshi","nawaz","aman","asmam"]

batch_1.reverse()
print(batch_3)
batch_2.reverse()
print(batch_4)
batch_3.reverse()
print(batch_3)
batch_4.reverse()
print(batch_4)
batch_5.reverse()
print(batch_5)
batch_6.reverse()
print(batch_6)
batch_7.reverse()
print(batch_7)
batch_8.reverse()
print(batch_8)
batch_9.reverse()
print(batch_9)
batch_10.reverse()
print(batch_10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[22, 11, 88, 33, 44, 55, 66, 77, 99]
[99, 88, 77, 66, 55, 44, 33, 22, 11]
[90, 40, 40, 40, 80, 70, 60, 50, 40, 30, 20, 10]
[0, 7, 5, 23, 76, 45, 65, 5, 32, 12]
[74, 45, 4, 12, 54, 13, 20, 92, 54, 32]
[11, 12, 10, 10, 10, 10, 10, 10, 13, 14, 15, 16, 17, 18, 19, 10]
[101, 100, 91, 81, 71, 61, 51, 41, 31, 21]
[44, 86, 32, 19, 17, 51, 51, 51, 61, 17, 26, 34, 61, 51, 41]
[59, 8, 4, 37, 26, 51, 64, 73, 82, 91]
['gopal', 'chandhu', 'aniketh', 'manoj', 'vardhan']
['raju', 'ramesh', 'SUresh', 'bheem', 'akhil']
['vardhan', 'manoj', 'aniketh', 'chandhu', 'gopal']
['akhil', 'bheem', 'SUresh', 'ramesh', 'raju']
['raju', 'prakash', 'vinith', 'vardhan', 'sri']
['mahesh', 'rajesh', 'vamsi', 'Venky', 'teja']
['manasa', 'navatha', 'sindhu', 'kavya', 'gopal']
['yash', 'nithin', 'ganesh', 'prashanth', 'charan']
['bhaSkar', 'vinay', 'Sai', 'akhil', 'sandeep', 'raghu']
['asmam', 'aman', 'nawaz', 'vamshi', 'fhanni']

In [7]:
#10) Copy
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,14,15,16,17,18,19,20]
list3 = list1.copy()
print(list3)
list4 = list4.copy()
print(list4)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [105]:
#11) change list items
batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
batch_1[2] = "koushik"
print(batch_1)
batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
batch_1[1:3] = "abc","cbd","bdc"
print(batch_1)

['vasu', 'kittu', 'koushik', 'lokEsh', 'shiva']
['vasu', 'abc', 'cbd', 'bdc', 'lokEsh', 'shiva']

In [112]:
#12) clear
batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
batch_clear = batch_1.clear()
print(batch_clear)

None

In [116]:
#13) length()
batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
len(batch_1)

5

In [118]:
#14) min()
batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
min(batch_1)

'Pranay'

In [120]:
#15) max()
batch_1 = ["vasu","kittu","Pranay","lokEsh","shiva"]
max(batch_1)

'vasu'