In [55]:
#String Operators
#1) Concatination (Combining two or more strings)
str1 = "Pra"
str2 = "nay"
str3 = "Reddy"
print(str1 + str2 +" " + str3)

A = "I am"
B = "a hero."
print(A +" "+ B)

X = "I am"
Y = " learning "
Z = "python."
print(X + Y + Z)

str1 = "I"
str2 = "will win."
print(str1+ " " + str2)

str1 = "I am "
str2 = "good at "
str3 = "speaking."
print(str1 + str2 + str3)

str1 = "we are"
str2 = "goining to "
str3 = "hyderabad"
print(str1 + " " + str2 + str3)

str1  = "we are studying "
str2 = "in vaagdevi college of engineering"
print(str1 + str2)

A = "abc "
B = "bcd"
print(A + B)

xyz = "A B C D"
pqr = "E F G H"
print(xyz + " " + pqr)

qwerty = "my name is "
name = "pranay reddy"
print(qwerty + name)

#2) Repetition
str1 = "Pra"
str2 = "nay"
str3 = "Reddy, "
result = (str1 + str2 +" " + str3)
print(result * 3)

A = "I am"
B = "a hero."
print((A +" "+ B) * 6)

str1 = "we are"
str2 = "goining to "
str3 = "hyderabad"
result = (str1 + " " + str2 + str3)
print(result * 7)

qwerty = "my name is "
name = "pranay reddy"
print((qwerty + name) * 4)

xyz = "A B C D"
pqr = "E F G H"
print((xyz + " " + pqr) * 5)

X = "I am"
Y = " learning "
Z = "python."
print((X + Y + Z) * 3)

talent1 = "cricket, "
talent2 = "kabaddi, "
talent3 = "kho-kho"
talents = talent1 + talent2 + talent3
print(talents * 4)

str1  = "we are studying "
str2 = "in vaagdevi college of engineering"
print((str1 + str2) * 2)

str1 = "I am "
str2 = "good at "
str3 = "speaking."
print((str1 + str2 + str3) * 2)

#3) Indexing
my_string = "I love myself"
print(my_string[3])

college = "Vaagdevi College of Engineering"
print(college[13])

Institute = "Teks academy"
print(Institute[2])

town = "sriramulapally"
print(town[5])

variable = "we have good institute"
print(variable[9])

vechicles = "bikes are very specials"
print(vechicles[10])

Bikes = "KTM bikes are very famous"
print(Bikes[15])

classes = "there are much classes in our school"
print(classes[20])

#4) Slicing
Institute = "Teks academy"
print(Institute[5 : 12])

company = "accenture"
print(company[1 : ])

classes = "there are much classes in our school"
print(classes[2 : 20])

variable = "we have good institute"
print(variable[0 : 10])

Bikes = "KTM bikes are very famous"
print(Bikes[2 : 15])

vechicles = "bikes are very specials"
print(vechicles[-10 : -1])

town = "sriramulapally"
print(town[5 : -5])

company = "accenture"
print(company[1 : 5])

my_string = "I love myself"
print(my_string[2 : 6])

Pranay Reddy
I am a hero.
I am learning python.
I will win.
I am good at speaking.
we are goining to hyderabad
we are studying in vaagdevi college of engineering
abc bcd
A B C D E F G H
my name is pranay reddy
Pranay Reddy, Pranay Reddy, Pranay Reddy,
I am a hero.I am a hero.I am a hero.I am a hero.I am a hero.I am a hero.
we are goining to hyderabadwe are goining to hyderabadwe are goining to hyderabadwe are goining to hyderabadwe are goining to hyderabadwe are goining to hyderabadwe are goining to hyderabad
my name is pranay reddymy name is pranay reddymy name is pranay reddymy name is pranay reddy
A B C D E F G HA B C D E F G HA B C D E F G HA B C D E F G HA B C D E F G H
I am learning python.I am learning python.I am learning python.
cricket, kabaddi, kho-khocricket, kabaddi, kho-khocricket, kabaddi, kho-khocricket, kabaddi, kho-kho
we are studying in vaagdevi college of engineeringwe are studying in vaagdevi college of engineering
I am good at speaking.I am good at speaking.
o
e
k
m
o
v
e
e
academy
ccenture
ere are much class
we have go
M bikes are v
y special
mula
ccen
love

In [89]:
#Formating String
#1) Old style format
company = "Revature"
location = "Hyderabad"
formatted_string = "I have been working in %s at %s for 2 years."%(company,location)
print(formatted_string)

jobs = 10
competition = "lot of people"
formatted_string = "There are %s for just %d openings."%(competition,jobs)
print(formatted_string)

no_of_fruits = "three"
types_of_fruits = "apples"
formatted_string = "He ate all the %s %s."%(no_of_fruits,types_of_fruits)
print(formatted_string)

abc = "upma"
cbd = 10
formatted_string = "I ate my tiffin %s in just %d minutes."%(abc,cbd)
print(formatted_string)

institute = "teks academy"
years = 15
formatted_string = "There is a institute called %s since %d years."%(institute,years)
print(formatted_string)

name = "pranay"
age = 22
formatted_string = "my name is %s and i am %d years old."%(name,age)
print(formatted_string)

vechicle = "bike"
time = 2
formatted_string = "I have went to college on my %s within %d hours."%(vechicle,time)
print(formatted_string)

place = "AMB mall"
no_of_people = 200
formatted_string = "There are %d members inside the %s."%(no_of_people,place)
print(formatted_string)

classes = 10
teacher = "swapna"
formatted_string = "%s teaches %d classes in a single day."%(teacher,classes)
print(formatted_string)

bikes = 12
people = 4
formatted_string = "for every %d people there are %d bikes."%(people,bikes)
print(formatted_string)

#2) format method
vechicle = "bike"
time = 2
formatted_string = "I have went to college on my {} within {} hours.".format(vechicle,time)
print(formatted_string)

place = "AMB mall"
no_of_people = 200
formatted_string = "There are {} members inside the {}.".format(no_of_people,place)
print(formatted_string)

name = "pranay"
age = 22
formatted_string = "my name is {} and i am {} years old.".format(name,age)
print(formatted_string)

bikes = 12
people = 4
formatted_string = "for every {} people there are {} bikes.".format(people,bikes)
print(formatted_string)

classes = 10
teacher = "swapna"
formatted_string = "{} teaches {} classes in a single day.".format(teacher,classes)
print(formatted_string)

institute = "teks academy"
years = 15
formatted_string = "There is a institute called {} since {} years.".format(institute,years)
print(formatted_string)

no_of_fruits = "three"
types_of_fruits = "apples"
formatted_string = "He ate all the {} {}.".format(no_of_fruits,types_of_fruits)
print(formatted_string)

jobs = 10
competition = "lot of people"
formatted_string = "There are {} for just {} openings.".format(competition,jobs)
print(formatted_string)

company = "Revature"
location = "Hyderabad"
formatted_string = "I have been working in {} at {} for 2 years.".format(company,location)
print(formatted_string)

abc = "upma"
cbd = 10
formatted_string = "I ate my tiffin {} in just {} minutes.".format(abc,cbd)
print(formatted_string)

#3) String interpolation (f-string)
place = "AMB mall"
no_of_people = 200
formatted_string = f"There are {no_of_people} members inside the {place}."
print(formatted_string)

jobs = 10
competition = "lot of people"
formatted_string = f"There are {competition} for just {jobs} openings."
print(formatted_string)

company = "Revature"
location = "Hyderabad"
formatted_string = f"I have been working in {company} at {location} for 2 years."
print(formatted_string)

no_of_fruits = "three"
types_of_fruits = "apples"
formatted_string = f"He ate all the {no_of_fruits} {types_of_fruits}."
print(formatted_string)

abc = "upma"
cbd = 10
formatted_string = f"I ate my tiffin {abc} in just {cbd} minutes."
print(formatted_string)

institute = "teks academy"
years = 15
formatted_string = f"There is a institute called {institute} since {years} years."
print(formatted_string)

name = "pranay"
age = 22
formatted_string = f"my name is {name} and i am {age} years old."
print(formatted_string)

vechicle = "bike"
time = 2
formatted_string = f"I have went to college on my {vechicle} within {time} hours."
print(formatted_string)

classes = 10
teacher = "swapna"
formatted_string = f"{teacher} teaches {classes} classes in a single day."
print(formatted_string)

bikes = 12
people = 4
formatted_string = f"for every {people} people there are {bikes} bikes."
print(formatted_string)

I have been working in Revature at Hyderabad for 2 years.
There are lot of people for just 10 openings.
He ate all the three apples.
I ate my tiffin upma in just 10 minutes.
There is a institute called teks academy since 15 years.
my name is pranay and i am 22 years old.
I have went to college on my bike within 2 hours.
There are 200 members inside the AMB mall.
swapna teaches 10 classes in a single day.
for every 4 people there are 12 bikes.
I have went to college on my bike within 2 hours.
There are 200 members inside the AMB mall.
my name is pranay and i am 22 years old.
for every 4 people there are 12 bikes.
swapna teaches 10 classes in a single day.
There is a institute called teks academy since 15 years.
He ate all the three apples.
There are lot of people for just 10 openings.
I have been working in Revature at Hyderabad for 2 years.
I ate my tiffin upma in just 10 minutes.
There are 200 members inside the AMB mall.
There are lot of people for just 10 openings.
I have been working in Revature at Hyderabad for 2 years.
He ate all the three apples.
I ate my tiffin upma in just 10 minutes.
There is a institute called teks academy since 15 years.
my name is pranay and i am 22 years old.
I have went to college on my bike within 2 hours.
swapna teaches 10 classes in a single day.
for every 4 people there are 12 bikes.

In [143]:
#String Method
#1) len()
Name = "Pranay Kanchanakuntla"
length = len(Name)
print(length)

Location = "My current location is Hyderabad"
length = len(Location)
print(length)

my_string = "i am leaving Hyderabad"
print(len(my_string))

skill = "I HAVE GOOD KNOWLEDGE IN PYTHOM"
print(len(skill))

sports = "I PLAY CRICKET WELL"
print(len(sports))

Village = " Sriramulapally      "
print(len(Village))

abc = "   we are good friends     "
print(len(abc))

City = "I am in Hanamkonda"
new_string = len(City)
print(new_string)

skills = "I have good idea on Python and SQL"
print(len(skills))

about = "Life has no Cntrl+Z"
print(len(about))

#2) lower() / upper()
my_string = "i am leaving Hyderabad"
print(my_string.upper())

name = "pranay"
uppercase = name.upper()
print(uppercase)

Location = "My current location is Hyderabad"
print(Location.upper())

skill = "I HAVE GOOD KNOWLEDGE IN PYTHOM"
print(skill.lower())

sports = "I PLAY CRICKET WELL"
print(sports.lower())

City = "HANAMKONDA AND WARANGAL"
print(City.lower())

names = "koushik and lokesh"
print(names.upper())

hostel = "DURGAM CHERUVU METRO STATION"
print(hostel.lower())

academy = "there are 15 members"
print(academy.upper())

heros = "PRABHAS AND NTR"
print(heros.upper())

#3) Strip()
Village = " Sriramulapally      "
print(Village.strip())

abc = "   we are good friends     "
print(abc.strip())

Location = "     My current    location is Hyderabad  "
print(Location.strip())

skill = "   I HAVE GOOD KNOWLEDGE IN PYTHOM"
print(skill.strip())

sports = "    I PLAY CRICKET WELL     "
print(sports.strip())

City = "HANAMKONDA AND WARANGAL"
print(City.strip())

names = "          koushik and lokesh             "
print(names.strip())

hostel = "          DURGAM CHERUVU METRO STATION                                  "
print(hostel.strip())

academy = "           there are             15 members           "
print(academy.strip())

heros = "      PRABHAS AND NTR           "
print(heros.strip())

#4) Replace
City = "I am in Hanamkonda"
new_string = City.replace("Hanamkonda","Hydearabad")
print(new_string)

skills = "I have good idea on Python and SQL"
print(skills.replace("idea on","knowledge in"))

Location = "My current location is Hyderabad"
print(Location.replace("My","Our"))

skill = "I HAVE GOOD KNOWLEDGE IN PYTHOM"
print(skill.replace("I","We"))

sports = "I PLAY CRICKET WELL"
print(sports.replace("CRICKET","kabaddi"))

City = "HANAMKONDA AND WARANGAL"
print(City.replace("HANAMKONDA","HYDERABAD"))

names = "koushik and lokesh"
print(names.replace("koushik","manoj"))

hostel = "DURGAM CHERUVU METRO STATION"
print(hostel.replace("CHERUVU"," "))

academy = "there are 15 members"
print(academy.replace("15","20"))

heros = "PRABHAS AND NTR"
print(heros.replace("NTR","MAHESH"))

#5) Spilt()
about = "Life has no Cntrl+Z"
print(about.split())

location = "I have been living in Hanamkonda for 22 years"
print(location.split())

skill = "I HAVE GOOD KNOWLEDGE IN PYTHOM"
print(skill.split())

sports = "I PLAY CRICKET WELL"
print(sports.split())

City = "HANAMKONDA AND WARANGAL"
print(City.split())

names = "koushik and lokesh"
print(names.split())

hostel = "DURGAM CHERUVU METRO STATION"
print(hostel.split())

academy = "there are 15 members"
print(academy.split())

heros = "PRABHAS AND NTR"
print(heros.split())

City = "I am in Hanamkonda"
new_string = City.split()
print(new_string)

#6) join()
about = ['Life', 'has', 'no', 'Cntrl+Z']
join_str = " ".join(about)
print(join_str)

location = ['I', 'have', 'been', 'living', 'in', 'Hanamkonda', 'for', '22', 'years']
print(' '.join(location))

skills = ['I', 'HAVE', 'GOOD', 'KNOWLEDGE', 'IN', 'PYTHOM']
print(' '.join(skills))

sports = ['I', 'PLAY', 'CRICKET', 'WELL']
print(' '.join(sports))

city = ['HANAMKONDA', 'AND', 'WARANGAL']
print(' '.join(city))

friends = ['koushik', 'and', 'lokesh']
print(' '.join(friends))

proper = ['DURGAM', 'CHERUVU', 'METRO', 'STATION']
print(' '.join(proper))

classes = ['there', 'are', '15', 'members']
print(' '.join(classes))

heros = ['PRABHAS', 'AND', 'NTR']
print(' '.join(heros))

present = ['I', 'am', 'in', 'Hanamkonda']
print(' '.join(present))

21
32
22
31
19
21
27
18
34
19
I AM LEAVING HYDERABAD
PRANAY
MY CURRENT LOCATION IS HYDERABAD
i have good knowledge in pythom
i play cricket well
hanamkonda and warangal
KOUSHIK AND LOKESH
durgam cheruvu metro station
THERE ARE 15 MEMBERS
PRABHAS AND NTR
Sriramulapally
we are good friends
My current    location is Hyderabad
I HAVE GOOD KNOWLEDGE IN PYTHOM
I PLAY CRICKET WELL
HANAMKONDA AND WARANGAL
koushik and lokesh
DURGAM CHERUVU METRO STATION
there are             15 members
PRABHAS AND NTR
I am in Hydearabad
I have good knowledge in Python and SQL
Our current location is Hyderabad
We HAVE GOOD KNOWLEDGE WeN PYTHOM
I PLAY kabaddi WELL
HYDERABAD AND WARANGAL
manoj and lokesh
DURGAM   METRO STATION
there are 20 members
PRABHAS AND MAHESH
['Life', 'has', 'no', 'Cntrl+Z']
['I', 'have', 'been', 'living', 'in', 'Hanamkonda', 'for', '22', 'years']
['I', 'HAVE', 'GOOD', 'KNOWLEDGE', 'IN', 'PYTHOM']
['I', 'PLAY', 'CRICKET', 'WELL']
['HANAMKONDA', 'AND', 'WARANGAL']
['koushik', 'and', 'lokesh']
['DURGAM', 'CHERUVU', 'METRO', 'STATION']
['there', 'are', '15', 'members']
['PRABHAS', 'AND', 'NTR']
['I', 'am', 'in', 'Hanamkonda']
Life has no Cntrl+Z
I have been living in Hanamkonda for 22 years
I HAVE GOOD KNOWLEDGE IN PYTHOM
I PLAY CRICKET WELL
HANAMKONDA AND WARANGAL
koushik and lokesh
DURGAM CHERUVU METRO STATION
there are 15 members
PRABHAS AND NTR
I am in Hanamkonda

In [147]:
#7) capitalize
names = "koushik and lokesh"
print(names.capitalize())

bike = "suzuki"
print(bike.capitalize())

Koushik and lokesh
Suzuki

In [157]:
#8) casefold (converts all into small letters)
names = "KOUSHIK and lokesh"
print(names.casefold())

bike = "suZuKi"
print(bike.casefold())

koushik and lokesh
suzuki

In [165]:
#9) endswith()
message = "python is fun"
print(message.endswith("fun"))

name = "pranay reddy"
print(name.endswith("pranay"))

True
False

In [171]:
#10) find()
message = "python is fun"
print(message.find("fun"))

bike = "suZuKi is my fav bike"
print(bike.find("fav"))

10
13

In [175]:
#11) isalnum()
name1 = "python3"
name2 = "python 3"
print(name1.isalnum())
print(name2.isalnum())

True
False

In [177]:
#12) isalpha()
name1 = "python"
name2 = "python3"
print(name1.isalpha())
print(name2.isalpha())

True
False

In [29]:
#13)isdecimal()
name1 = "python3"
name2 = "python"
name3 = "1332"
print(name1.isdecimal())
print(name2.isdecimal())
print(name3.isdecimal())

False
False
True

In [198]:
#14)startswith
message = "python is fun"
print(message.startswith("python"))
print(message.startswith("is"))

True
False

In [208]:
#15) isprintable
text = "apple"
result = text.isprintable()
print(result)

True

In [33]:
#16) isalnum()
name1 = "python3"
name2 = "python 3"
name3 = "1332"
print(name1.isalnum())
print(name2.isalnum())
print(name3.isalnum())

True
False
True

In [25]:
#17) isdigit()
name1 = "python3"
name2 = "python"
name3 = "1332"
print(name1.isdigit())
print(name2.isdigit())
print(name3.isdigit())

False
False
True

In [37]:
#18) istitle()
about = "Python Is Fun For All"
print(about.istitle())

name = "my Name Is Pranay"
print(name.istitle())

True
False

In [43]:
#19) isupper()
about = "Python Is Fun For All"
print(about.isupper())
about2 = "PYTHON IS FUN FOR ALL"
print(about2.isupper())

False
True

In [47]:
#20) islower()
about = "Python Is Fun For All"
print(about.islower())
about2 = "python is fun for all"
print(about2.islower())

False
True

In [55]:
#21) splitlines()
about = "Python\nIs\nFun\nFor\nAll"
print(about.splitlines())
name = "Her\nname\nis\nsindhu"
print(name.splitlines())

['Python', 'Is', 'Fun', 'For', 'All']
['Her', 'name', 'is', 'sindhu']

In [61]:
#22) swapcase()
about = "Python Is Fun For All"
print(about.swapcase())
name = "Her is name sindhu"
print(name.swapcase())

pYTHON iS fUN fOR aLL
hER IS NAME SINDHU

In [71]:
#23) zfill()
about = "Python Is Fun For All"
print(about.zfill(25))
name = "Her is name sindhu"
print(name.zfill(30))

0000Python Is Fun For All
000000000000Her is name sindhu